backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
i18n:
  structure: multiple_folders
  locales: [es, ca]
  default_locale: ca
media_folder: "apps/dracs/public/images"
public_folder: "apps/dracs/public/images"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    i18n: true
    folder: "apps/dracs/src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      # - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "publishDate", widget: "datetime" }
      # - { label: "Featured Image", name: "thumbnail", widget: "image" }
      # - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - {
          label: "Language",
          name: "lang",
          widget: "select",
          options: ["es", "ca"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
